### ISSUE TITLE
C# bots appear as C

### ISSUE THREAD

**Issue by swz-git** [VirxEC/rlbot_gui_rust#1]
![](https://swz.works/chest/ZA-i2m.png)
I'm guessing that this is because it reads the # symbol as a comment

**Comment by VirxEC** [comment]
That's quite an interesting thing! I don't think the Python GUI recognizes comments, so I'll tell configparser to only recognize `;` as the start of a comment (is `;` and `#` by default)

https://docs.rs/configparser/3.0.0/configparser/ini/struct.Ini.html#method.set_comment_symbols

Fixed in next release, `1.0.6`
